Patch to fix implicit declaration warning/error (#2)
When compiling gnuski on macOS sonoma, the following error is raised due to an implicit declaration:

```
gcc -O2 -o gnuski main.c objects.c -lncurses
main.c:45:3: error: call to undeclared function 'setupColors'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
setupColors ();
^
```

This patches fixes this issue.

Originally created on 2023-10-15 by Thierry Moisan: https://sourceforge.net/p/gnuski/patches/2/